import type express from "express";
import type { ServerRouteContext } from "../server-context";
import { registerApiCorsMiddleware } from "./api-cors";
import { registerAgentRoutes } from "./agent-routes";
import { registerChannelRoutes } from "./channel-routes";
import { registerCommunicationEmailRoutes } from "./communication-email-routes";
import { registerConversationRoutes } from "./conversation-routes";
import { registerCoreRoutes } from "./core-routes";
import { registerHumanReplyRoutes } from "./human-reply-routes";
import { registerDeviceRoutes } from "./device-routes";
import { registerExecutionRoutes } from "./execution-routes";
import { registerGovernanceRoutes } from "./governance-routes";
import { registerHelpdeskSignupRoutes } from "./helpdesk-signup-routes";
import { registerHeartbeatRoutes } from "./heartbeat-routes";
import { registerInternalAgentRoutes } from "./internal-agent-routes";
import { registerMachineOnboardingPublicRoutes, registerMachineOnboardingRoutes } from "./machine-onboarding-routes";
import { registerMachineRoutes } from "./machine-routes";
import { registerMcpRoutes } from "./mcp-routes";
import { registerMobileAppRoutes } from "./mobile-app-routes";
import { registerOperatorRoutes } from "./operator-routes";
import { registerResourceGrantRoutes } from "./resource-grant-routes";
import { registerRuntimeExecutionRoutes } from "./runtime-execution-routes";
import { registerSharedFileRoutes } from "./shared-file-routes";
import { registerTaskMessageRoutes } from "./task-message-routes";
import { registerTelegramRoutes } from "./telegram-routes";
import { registerWorkspaceBridgeRoutes } from "./workspace-bridge-routes";
import { registerWorkspaceRoutes } from "./workspace-routes";
import { registerWebApiEnvelopeMiddleware } from "./web-api-envelope";

export function registerHttpRoutes(app: express.Express, ctx: ServerRouteContext): void {
  registerApiCorsMiddleware(app);
  registerWebApiEnvelopeMiddleware(app);
  registerMcpRoutes(app, ctx);
  registerMobileAppRoutes(app, ctx);
  registerMachineOnboardingPublicRoutes(app, ctx);
  registerHelpdeskSignupRoutes(app, ctx);
  registerTelegramRoutes(app, ctx);
  registerOperatorRoutes(app, ctx);
  registerHeartbeatRoutes(app, ctx);
  registerSharedFileRoutes(app, ctx);
  registerCoreRoutes(app, ctx);
  registerHumanReplyRoutes(app, ctx);
  registerGovernanceRoutes(app, ctx);
  registerWorkspaceRoutes(app, ctx);
  registerWorkspaceBridgeRoutes(app, ctx);
  registerDeviceRoutes(app, ctx);
  registerResourceGrantRoutes(app, ctx);
  registerChannelRoutes(app, ctx);
  registerConversationRoutes(app, ctx);
  registerMachineOnboardingRoutes(app, ctx);
  registerMachineRoutes(app, ctx);
  registerAgentRoutes(app, ctx);
  registerCommunicationEmailRoutes(app, ctx);
  registerExecutionRoutes(app, ctx);
  registerRuntimeExecutionRoutes(app, ctx);
  registerTaskMessageRoutes(app, ctx);
  registerInternalAgentRoutes(app, ctx);
}
